### ISSUE TITLE
Different Groups of Applications

### ISSUE THREAD

**Issue by TBThomas56** [DiamondLightSource/logpanel#4]
Display from whole group of applications / beamline (2 separate)
- To select a deployment of GDA for a specific beamline
- To select a set of containers on a given kubernetes cluster
The second one is harder and we may actually have to label the containers so they are easier to find in the graylog metadata, so I would suggest just concentrating on the first case for now

**Comment by callumforrester** [comment]
More specific...

As a user I want to filter my logs by beamline and application name so that I can narrow them down to only logs that are relevant to something I am testing/debugging.

## Acceptance Criteria
- GUI item for beamline (text field)
- GUI item for application name (text field)
- Logs displayed are only from beamline matching beamline field and application matching application field
- If application field is empty, logs displayed are only from beamline matching beamline field
- If beamline field is empty, no logs are displayed at all, multi-beamline logs are currently out of scope
