### ISSUE TITLE
Log Filtering (Level)

### ISSUE THREAD

**Issue by TBThomas56** [DiamondLightSource/logpanel#9]
Filter through logs, how would Unknown Level be handled?

**Comment by callumforrester** [comment]
As a user I want to select a minimum log level (ERROR, INFO, etc.) to display and only see those logs so that I can filter out large amounts of repeated debugging data when I don't need to see it.

## Acceptance Criteria
- GUI item to select minimum log level
- Only logs as severe or more than the selected level are displayed
